// Mocks generated by Mockito 5.4.6 from annotations
// in movie_discovery_app/test/unit/usecases/get_movie_details_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:movie_discovery_app/core/errors/failures.dart' as _i5;
import 'package:movie_discovery_app/features/movies/domain/entities/movie.dart'
    as _i6;
import 'package:movie_discovery_app/features/movies/domain/entities/video.dart'
    as _i8;
import 'package:movie_discovery_app/features/movies/domain/repositories/movie_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i2.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>> getPopularMovies(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [page],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Movie>>>(
          this,
          Invocation.method(
            #getPopularMovies,
            [page],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>> getTopRatedMovies(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [page],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Movie>>>(
          this,
          Invocation.method(
            #getTopRatedMovies,
            [page],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>> getUpcomingMovies(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingMovies,
          [page],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Movie>>>(
          this,
          Invocation.method(
            #getUpcomingMovies,
            [page],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>> searchMovies(
    String? query,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [
            query,
            page,
          ],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Movie>>>(
          this,
          Invocation.method(
            #searchMovies,
            [
              query,
              page,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Movie>> getMovieDetails(
          int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetails,
          [movieId],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.Movie>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i6.Movie>>(
          this,
          Invocation.method(
            #getMovieDetails,
            [movieId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.Movie>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.Video>>> getMovieVideos(
          int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieVideos,
          [movieId],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, List<_i8.Video>>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.Video>>>(
          this,
          Invocation.method(
            #getMovieVideos,
            [movieId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i8.Video>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>> getFavoriteMovies(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteMovies,
          [userId],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Movie>>>(
          this,
          Invocation.method(
            #getFavoriteMovies,
            [userId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> addToFavorites(
    String? userId,
    int? movieId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [
            userId,
            movieId,
          ],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #addToFavorites,
            [
              userId,
              movieId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> removeFromFavorites(
    String? userId,
    int? movieId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [
            userId,
            movieId,
          ],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #removeFromFavorites,
            [
              userId,
              movieId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, bool>> isFavorite(
    String? userId,
    int? movieId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [
            userId,
            movieId,
          ],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, bool>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, bool>>(
          this,
          Invocation.method(
            #isFavorite,
            [
              userId,
              movieId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, bool>>);
}
