// Mocks generated by Mockito 5.4.6 from annotations
// in movie_discovery_app/test/unit/repositories/movie_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_discovery_app/features/movies/data/datasources/local/movie_local_data_source.dart'
    as _i6;
import 'package:movie_discovery_app/features/movies/data/datasources/remote/movie_remote_data_source.dart'
    as _i4;
import 'package:movie_discovery_app/features/movies/data/models/movie_model.dart'
    as _i2;
import 'package:movie_discovery_app/features/movies/data/models/video_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieListResponse_0 extends _i1.SmartFake
    implements _i2.MovieListResponse {
  _FakeMovieListResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieModel_1 extends _i1.SmartFake implements _i2.MovieModel {
  _FakeMovieModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoListResponse_2 extends _i1.SmartFake
    implements _i3.VideoListResponse {
  _FakeVideoListResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i4.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.MovieListResponse> getPopularMovies(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [page],
        ),
        returnValue:
            _i5.Future<_i2.MovieListResponse>.value(_FakeMovieListResponse_0(
          this,
          Invocation.method(
            #getPopularMovies,
            [page],
          ),
        )),
      ) as _i5.Future<_i2.MovieListResponse>);

  @override
  _i5.Future<_i2.MovieListResponse> getTopRatedMovies(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [page],
        ),
        returnValue:
            _i5.Future<_i2.MovieListResponse>.value(_FakeMovieListResponse_0(
          this,
          Invocation.method(
            #getTopRatedMovies,
            [page],
          ),
        )),
      ) as _i5.Future<_i2.MovieListResponse>);

  @override
  _i5.Future<_i2.MovieListResponse> getUpcomingMovies(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingMovies,
          [page],
        ),
        returnValue:
            _i5.Future<_i2.MovieListResponse>.value(_FakeMovieListResponse_0(
          this,
          Invocation.method(
            #getUpcomingMovies,
            [page],
          ),
        )),
      ) as _i5.Future<_i2.MovieListResponse>);

  @override
  _i5.Future<_i2.MovieListResponse> searchMovies(
    String? query,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [
            query,
            page,
          ],
        ),
        returnValue:
            _i5.Future<_i2.MovieListResponse>.value(_FakeMovieListResponse_0(
          this,
          Invocation.method(
            #searchMovies,
            [
              query,
              page,
            ],
          ),
        )),
      ) as _i5.Future<_i2.MovieListResponse>);

  @override
  _i5.Future<_i2.MovieModel> getMovieDetails(int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetails,
          [movieId],
        ),
        returnValue: _i5.Future<_i2.MovieModel>.value(_FakeMovieModel_1(
          this,
          Invocation.method(
            #getMovieDetails,
            [movieId],
          ),
        )),
      ) as _i5.Future<_i2.MovieModel>);

  @override
  _i5.Future<_i3.VideoListResponse> getMovieVideos(int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieVideos,
          [movieId],
        ),
        returnValue:
            _i5.Future<_i3.VideoListResponse>.value(_FakeVideoListResponse_2(
          this,
          Invocation.method(
            #getMovieVideos,
            [movieId],
          ),
        )),
      ) as _i5.Future<_i3.VideoListResponse>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i6.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.MovieModel>> getCachedMovies() => (super.noSuchMethod(
        Invocation.method(
          #getCachedMovies,
          [],
        ),
        returnValue: _i5.Future<List<_i2.MovieModel>>.value(<_i2.MovieModel>[]),
      ) as _i5.Future<List<_i2.MovieModel>>);

  @override
  _i5.Future<List<_i2.MovieModel>> getCachedMoviesByIds(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedMoviesByIds,
          [ids],
        ),
        returnValue: _i5.Future<List<_i2.MovieModel>>.value(<_i2.MovieModel>[]),
      ) as _i5.Future<List<_i2.MovieModel>>);

  @override
  _i5.Future<void> cacheMovies(List<_i2.MovieModel>? movies) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheMovies,
          [movies],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cacheMovie(_i2.MovieModel? movie) => (super.noSuchMethod(
        Invocation.method(
          #cacheMovie,
          [movie],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<int>> getFavoriteMovieIds(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteMovieIds,
          [userId],
        ),
        returnValue: _i5.Future<List<int>>.value(<int>[]),
      ) as _i5.Future<List<int>>);

  @override
  _i5.Future<void> addToFavorites(
    String? userId,
    int? movieId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [
            userId,
            movieId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeFromFavorites(
    String? userId,
    int? movieId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [
            userId,
            movieId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isFavorite(
    String? userId,
    int? movieId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [
            userId,
            movieId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
