// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpyGXhKUsL10qxo18bkr85_C1iGYTFjIs',
    appId: '1:9105530153:web:4f8d0018236c9fc467eb38',
    messagingSenderId: '9105530153',
    projectId: 'movie-discover-9c501',
    authDomain: 'movie-discover-9c501.firebaseapp.com',
    storageBucket: 'movie-discover-9c501.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsIApqKoxJVTf7txU4dR0lZcvOL55ZW1E',
    appId: '1:9105530153:android:7ed6e6904317ae4467eb38',
    messagingSenderId: '9105530153',
    projectId: 'movie-discover-9c501',
    storageBucket: 'movie-discover-9c501.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpyGXhKUsL10qxo18bkr85_C1iGYTFjIs',
    appId: '1:9105530153:ios:4f8d0018236c9fc467eb38',
    messagingSenderId: '9105530153',
    projectId: 'movie-discover-9c501',
    storageBucket: 'movie-discover-9c501.firebasestorage.app',
    iosBundleId: 'com.example.movieDiscoveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpyGXhKUsL10qxo18bkr85_C1iGYTFjIs',
    appId: '1:9105530153:ios:4f8d0018236c9fc467eb38',
    messagingSenderId: '9105530153',
    projectId: 'movie-discover-9c501',
    storageBucket: 'movie-discover-9c501.firebasestorage.app',
    iosBundleId: 'com.example.movieDiscoveryApp',
  );
}
